# Generated by Django 6.0.2 on 2026-02-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
